---

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true


flag_management: {}

ignore:
  - "src/api-mocks/*"
  - "src/story-utils/*"
  - "src/**/mocks.{js,jsx}"
